import { Vehicle, Dealer, Area, Enquiry } from './types';

export const HYDERABAD_AREAS = [
  'Kukatpally',
  'LB Nagar',
  'Uppal',
  'Miyapur',
  'Gachibowli',
  'Secunderabad',
  'Hitech City',
  'Banjara Hills',
  'Jubilee Hills',
  'Madhapur',
  'Kondapur',
  'Ameerpet',
  'Begumpet',
  'Dilsukhnagar',
  'Charminar',
  'Mehdipatnam'
];

export const AREAS: Area[] = [
  { name: 'Kukatpally', count: 124 },
  { name: 'LB Nagar', count: 85 },
  { name: 'Uppal', count: 62 },
  { name: 'Miyapur', count: 94 },
  { name: 'Gachibowli', count: 112 },
  { name: 'Secunderabad', count: 145 },
];

export const DEALERS: Dealer[] = [
  {
    id: 'd1',
    name: 'Hyderabad Auto Hub',
    logo: 'https://picsum.photos/seed/autohub/200/200',
    area: 'Kukatpally',
    rating: 4.8,
    vehicleCount: 45,
    address: 'Plot 45, Beside Metro Station, Kukatpally, Hyderabad',
    phone: '+91 98765 43210',
    whatsapp: '+91 98765 43210',
    isVerified: true,
    joinedDate: '2023-01-15',
  },
  {
    id: 'd2',
    name: 'Elite Motors',
    logo: 'https://picsum.photos/seed/elitemotors/200/200',
    area: 'Gachibowli',
    rating: 4.5,
    vehicleCount: 32,
    address: 'Cyber Towers Road, Gachibowli, Hyderabad',
    phone: '+91 98765 43211',
    whatsapp: '+91 98765 43211',
    isVerified: true,
    joinedDate: '2023-03-20',
  },
  {
    id: 'd3',
    name: 'City Wheels',
    logo: 'https://picsum.photos/seed/citywheels/200/200',
    area: 'Secunderabad',
    rating: 4.2,
    vehicleCount: 28,
    address: 'MG Road, Secunderabad, Hyderabad',
    phone: '+91 98765 43212',
    whatsapp: '+91 98765 43212',
    isVerified: false,
    joinedDate: '2023-05-10',
  },
];

export const VEHICLES: Vehicle[] = [
  {
    id: 'v1',
    title: '2021 Honda City ZX',
    brand: 'Honda',
    model: 'City',
    year: 2021,
    price: 1250000,
    kmDriven: 25000,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    area: 'Kukatpally',
    type: 'Car',
    images: ['https://picsum.photos/seed/hondacity/800/600', 'https://picsum.photos/seed/hondacity2/800/600'],
    description: 'Well maintained Honda City ZX. Single owner, full insurance covered. No accidents.',
    dealerId: 'd1',
    isFeatured: true,
    status: 'Approved',
    createdAt: '2024-02-15',
  },
  {
    id: 'v2',
    title: '2019 Royal Enfield Classic 350',
    brand: 'Royal Enfield',
    model: 'Classic 350',
    year: 2019,
    price: 165000,
    kmDriven: 18000,
    fuelType: 'Petrol',
    transmission: 'Manual',
    area: 'Gachibowli',
    type: 'Bike',
    images: ['https://picsum.photos/seed/classic350/800/600'],
    description: 'Mint condition Classic 350. Gunmetal Grey color. Service records available.',
    dealerId: 'd2',
    isFeatured: true,
    status: 'Approved',
    createdAt: '2024-02-20',
  },
  {
    id: 'v3',
    title: '2022 Hyundai Creta SX',
    brand: 'Hyundai',
    model: 'Creta',
    year: 2022,
    price: 1580000,
    kmDriven: 12000,
    fuelType: 'Diesel',
    transmission: 'Manual',
    area: 'Secunderabad',
    type: 'Car',
    images: ['https://picsum.photos/seed/creta/800/600'],
    description: 'Almost new Hyundai Creta. Diesel variant with great mileage. Panoramic sunroof included.',
    dealerId: 'd3',
    status: 'Approved',
    createdAt: '2024-02-25',
  },
  {
    id: 'v4',
    title: '2020 Maruti Suzuki Swift VXI',
    brand: 'Maruti Suzuki',
    model: 'Swift',
    year: 2020,
    price: 620000,
    kmDriven: 35000,
    fuelType: 'Petrol',
    transmission: 'Manual',
    area: 'LB Nagar',
    type: 'Car',
    images: ['https://picsum.photos/seed/swift/800/600'],
    description: 'Excellent condition Swift. Regularly serviced at authorized centers.',
    dealerId: 'd1',
    status: 'Approved',
    createdAt: '2024-03-01',
  },
];

export const ENQUIRIES: Enquiry[] = [
  {
    id: 'e1',
    vehicleId: 'v1',
    buyerName: 'Rahul Sharma',
    buyerPhone: '+91 99887 76655',
    message: 'Interested in the Honda City. Is the price negotiable?',
    date: '2024-03-01',
  },
];
